### ISSUE TITLE
SAMD51 support

### ISSUE THREAD

**Issue by posixPilot** [SodaqMoja/Sodaq_wdt#3]
Hi,

Are there any plans to support the SAMD51 boards such as the Adafruit Metro Express M4?  Currently the compile fails with errors like:

Sodaq_wdt.cpp:47:7: error: 'struct Pm' has no member named 'APBAMASK'
   PM->APBAMASK.reg |= PM_APBAMASK_WDT;
odaq_wdt.cpp:47:23: error: 'PM_APBAMASK_WDT' was not declared in this scope
   PM->APBAMASK.reg |= PM_APBAMASK_WDT;
Sodaq_wdt.cpp:50:14: error: 'struct Wdt' has no member named 'CTRL'
   if (!(WDT->CTRL.reg & WDT_CTRL_ALWAYSON)) {

etc, etc

I am able to compile this by selecting a SAMD21 based board such as the Adafruit Feather M0, so I assume that SAMD51 support does not yet exist.

  Thanks
  Mike

**Comment by itayd100** [comment]
Hi Mike,

For now we are not supporting the SAMD51. Maybe in the future :)

Best regards,
Itay
